### ISSUE TITLE
Give customer Pterodactyl panel credentials in the welcome mail send with package

### ISSUE THREAD

**Issue by tompointexe** [blesta/module-pterodactyl#36]
Hi, i would like to know if we could send to the customer their pterodactyl credentials within the package welcome mail 
Thanks for answering

**Comment by JReissmueller** [comment]
That is not currently possible, though it could be with relatively simple changes.  However, the username and password are visible to the client if they click and expand the service row in the services widget on their profile page.

**Comment by tompointexe** [comment]
Ok, thanks for all this information, have a great day
