### ISSUE TITLE
Configurable Options

### ISSUE THREAD

**Issue by Pomdre** [blesta/module-pterodactyl#37]
It would have been nice to be able to configure eggid and memory as configurable options.

**Comment by JReissmueller** [comment]
I could see an argument for memory, but eggid?  That completely changes the kind of product they are ordering and fields they are required to submit.

**Comment by Pomdre** [comment]
Yes. then you can choose between spigot or papper mc for example.

**Comment by Pomdre** [comment]
But maybe just choosing memory could have been better

**Comment by JReissmueller** [comment]
Did you close this because of the lack of response?

**Comment by Pomdre** [comment]
> Did you close this because of the lack of response?

Yes I did, After all, it is not a problem but a suggestion. Label it as suggestion...
