### ISSUE TITLE
Egg not showing up when rest of fields filled in

### ISSUE THREAD

**Issue by Keystirras** [blesta/module-pterodactyl#42]
When creating a package using the module, sometimes the Egg ID's won't show when you fill in the rest of the drop down menus, 

"To reproduce, I selected the Server Group, Server, Location, and then the Nest. Eggs appear blank. Then I change the Server Group with the rest of the filled data, I get the egg ID from the currently selected nest. When changing the Nest, the Egg ID's don't update and I'm left with whatever IDs were in the Nest that was selected."

https://gyazo.com/d09bc439591c524d10cd74b8b4ed4d21
https://gyazo.com/708b96ba70a2a90fede390ef651b2ff3

**Comment by JReissmueller** [comment]
Looks like this is actually an issue with Blesta core.  In app/views/admin/default/admin_packages_moduleoptions.  Replace array_merge with array_merge_recursive on line 56. https://dev.blesta.com/browse/CORE-3679

**Comment by JReissmueller** [comment]
This was an issue create in 4.9 and is resolved as of 4.10.2
