### ISSUE TITLE
Support for Pterodactyl 1.0.x?

### ISSUE THREAD

**Issue by Snicon** [blesta/module-pterodactyl#49]
As I've understood it the release of Pterodactyl 1.0 comes with a new and re-written API and back-end, can anyone confirm this module is compatible with Pterodactyl 1.0.x? I haven't tried upgrading in fear of messing something up.

**Comment by pmphillips** [comment]
The module is not compatible with Pterodactyl 1.0 yet. It will be updated, but we don't have an ETA on that yet. We are evaluating the changes to the API.

**Comment by ThisIsSet-L** [comment]
We narrowed it down in our own testing to the "deploy" part. The user creation passes, but when it comes to create the server, the module sends, as an example:
```
{
  "external_id": "1-5f853385ab6fc",
  "name": "somename",
  "description": "Test Server for Enjin intergration",
  "user": 2,
  "nest": "1",
  "egg": "5",
  "pack": "",
  "docker_image": "quay.io/pterodactyl/core:java",
  "startup": "java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar {{SERVER_JARFILE}}",
  "limits": {
    "memory": "1024",
    "swap": "1024",
    "io": "500",
    "cpu": "200",
    "disk": "8192"
  },
  "feature_limits": {
    "databases": null,
    "allocations": null
  },
  "deploy": {
    "locations": [
      "1"
    ],
    "dedicated_ip": "0",
    "port_range": [
      "9000-10000"
    ]
  },
  "environment": {
    "SERVER_JARFILE": "server.jar",
    "VANILLA_VERSION": "latest"
  },
  "start_on_completion": true
}
```

The part Pterodactyl v1 gets hung up on is the "deploy" part. We reviewed the code in Pterodactyl v1, and we do see that the "deploy" feature is supposed to be in there, but it's hitting an error. If we remove the "deploy" section, and replace it with "allocation", as below, this works:
```
{
  "name": "somename",
  "description": "Test Server for Enjin intergration",
  "user": 2,
  "nest": "1",
  "egg": "5",
  "pack": "",
  "docker_image": "quay.io/pterodactyl/core:java",
  "startup": "java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar {{SERVER_JARFILE}}",
  "limits": {
    "memory": "1024",
    "swap": "1024",
    "io": "500",
    "cpu": "200",
    "disk": "8192"
  },
  "feature_limits": {
    "databases": 0,
    "allocations": 0
  },
  "allocation": {
    "default": 2,
    "additional": [
      5
    ]
  },
  "environment": {
    "SERVER_JARFILE": "server.jar",
    "VANILLA_VERSION": "latest"
  },
  "start_on_completion": true
}
```

I think there's something broken under the hood in Pterodactyl. We're still trying to figure out what exactly.

**Comment by JReissmueller** [comment]
Looks like this is an issue on their end https://github.com/pterodactyl/panel/issues/2529

**Comment by Pomdre** [comment]
Something new? Or maybe an ETA?

**Comment by JReissmueller** [comment]
If you download 1.5.1 and the latest pterodactyl then it should work fine.  Don't download 1.6.0 unless you are testing with Blesta 5.0 since it uses the newer versions of bootstrap and font awesome

**Comment by Pomdre** [comment]
Blesta Installed Version 4.12.3 Latest version of the panel and module verion 1.5.1
When someone orders a package, they are sent to a page whithe out content.
Try it your self https://kunde.fjellserver.no/order/main/packages/Minecraft/?group_id=5

**Comment by Pomdre** [comment]
> Blesta Installed Version 4.12.3 Latest version of the panel and module verion 1.5.1
> When someone orders a package, they are sent to a page whithe out content.
> Try it your self https://kunde.fjellserver.no/order/main/packages/Minecraft/?group_id=5

Maybe next time google before asking.. Sorry (https://www.blesta.com/forums/index.php?/topic/10511-blesta-logs-permission-error-causes-white-screen/)
