### ISSUE TITLE
Blesta cannot process transactions if the person is already a subuser on another server

### ISSUE THREAD

**Issue by kakduman** [blesta/module-pterodactyl#55]
Blesta accepts payment but cannot successfully execute the create server action for new people if they already have access to a server because the user already exists and it tries to create a new account with the same email. Instead, Blesta should just give the new server to the already-existing user.

## Steps to reproduce
1. Create a server in Pterodactyl with the owner "tim@example.com"
2. Add a subuser to that server with the email "bob@example.com"
3. Purchase hosting through Blesta using the email "bob@example.com"
4. Observe that Blesta accepts Bob's payment without throwing any errors, but cannot give Bob his server because an account with the same email already exists.

WHMCS does not have this bug, so feel free to look at the source code for the WHMCS module for a potential fix: https://github.com/pterodactyl/whmcs/blob/master/pterodactyl/pterodactyl.php

**Comment by astrooom** [comment]
Bump

**Comment by Jacksharkben** [comment]
I Would like to bump we have the same issue and everything has stopped.

**Comment by JReissmueller** [comment]
Just want to clarify, the desired behavior is that the order be rejected?

**Comment by Jacksharkben** [comment]
> Just want to clarify, the desired behavior is that the order be rejected?

no for me it just says failed to make an account. already exists.
and stays as pinding

**Comment by kakduman** [comment]
> Just want to clarify, the desired behavior is that the order be rejected?

No. The desired behavior is for the order to be accepted but for the server to be given to the currently existing account associated with the email address of the Blesta user rather than attempting to create a new account under that email address

**Comment by JReissmueller** [comment]
Understood.

**Comment by Jacksharkben** [comment]
any updates to this?

**Comment by JReissmueller** [comment]
Thanks for the followup.  I've scheduled this for Blesta 5.3 and I'll be sure to update this thread when the task is complete.

**Comment by sm0862512** [comment]
> Thanks for the followup.  I've scheduled this for Blesta 5.3 and I'll be sure to update this thread when the task is complete.

Yay thanks !

**Comment by JReissmueller** [comment]
Looks like I forgot to update this issue.  But this was indeed resolved in 5.3 as a part of [CORE-4427](https://dev.blesta.com/browse/CORE-4427)

**Comment by JReissmueller** [comment]
This is the PR that fixed it #63
