### ISSUE TITLE
Allow setting

### ISSUE THREAD

**Issue by SkippTekk** [blesta/module-pterodactyl#65]
To the docs of Ptero, we can use **-1** to give unlimited Swap. Please enable it as an option. https://gyazo.com/f829b8a832a89a3abd61b8904fee913f

**Comment by Pomdre** [comment]
Whay do you want to use swap in the first place..

**Comment by JReissmueller** [comment]
See [CORE-4681](https://dev.blesta.com/browse/CORE-4681).  Hotfix is in the task.

**Comment by JReissmueller** [comment]
Resolved by #74
