### ISSUE TITLE
Creting node not allowing ports only ip or domain

### ISSUE THREAD

**Issue by Pomdre** [blesta/module-pterodactyl#66]
When you are seting up a new server and adding it to blesta. 
Blesta does not allow you to specify ip:port only ip and domains are allowed.
This is annoying when setting up a test server on the same server for testing.

![image](https://user-images.githubusercontent.com/30056774/149006452-39a77bae-31a5-40fe-ac1f-573e93cd54be.png)

**Comment by JReissmueller** [comment]
See [CORE-4682](https://dev.blesta.com/browse/CORE-4682). Hotfix is in the task.

**Comment by JReissmueller** [comment]
Resolved by #75
