### ISSUE TITLE
Error with egg_id as an option

### ISSUE THREAD

**Issue by Pomdre** [blesta/module-pterodactyl#69]
When using a "Configurable Options that Override Package Options" with this problem egg_id as a option you will get an error that says "The Spigot Version variable field is required." The field is filled in as "latest" and is configured to have it as standard in ptero.

Blesta Installed Version 5.4.0

![image](https://user-images.githubusercontent.com/30056774/170573349-eed1d708-5a2c-4400-b5c0-02943cc6c3f1.png)

**Comment by Pomdre** [comment]
It seems that it does not send the values ​​set in blesta to pto

**Comment by Pomdre** [comment]
Logs
![image](https://user-images.githubusercontent.com/30056774/171048668-82f502cd-d533-4137-9f67-e03ccef23a4b.png)

![image](https://user-images.githubusercontent.com/30056774/171048595-df030ed9-d0ad-4e0c-86bc-605c97a23d26.png)

**Comment by Pomdre** [comment]
It is sending MINECRAFT_VERSION to petro and not BUNGEE_VERSION

**Comment by JReissmueller** [comment]
I think some updates to the core may have busted this functionality.  [CORE-4683](https://dev.blesta.com/browse/CORE-4683)

**Comment by JReissmueller** [comment]
See the comments on the task for a potential fix,

**Comment by JReissmueller** [comment]
Should be resolved by #70
