### ISSUE TITLE
"Unkown named parameter $nest_id"

### ISSUE THREAD

**Issue by staalexa** [blesta/module-pterodactyl#77]
Logs of Blesta
```
general.ERROR: Uncaught Exception Error: "Unknown named parameter $nest_id" at /var/www/html/components/modules/pterodactyl/pterodactyl.php line 937 {"exception":"[object] (Error(code: 0): Unknown named parameter $nest_id at /var/www/html/components/modules/pterodactyl/pterodactyl.php:937)"}
```

When creating a new server, browser gets an http 500 error and nothing happens. Apparently has to do with php8+

**Comment by JReissmueller** [comment]
"call_user_func_array() array keys will now be interpreted as parameter names, instead of being silently ignored." - https://www.php.net/manual/en/migration80.incompatible.php  I'll create a task for Blesta
